- name: playbook control using ansible facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx in redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Redhat"